### ISSUE TITLE
Extra P Tag in Drop Down Menu of Editor in TW 5.2.6

### ISSUE THREAD

**Issue by kookma** [flibbles/tw5-uglify#7] opened 2023-03-23 16:44 UTC
I used uglify to compress the empty Tiddlywiki 5.2.6. everything works fine. But I noticed the drop-down menu for selecting type of preview has an extra p tag.

**After uglifying**
![img_234_msedge](https://user-images.githubusercontent.com/830394/227278823-40d52edd-a4e7-497f-bc0e-e19fbafed55c.png)

Using inspect in Chrome shows: 

```
<p>✓</p>
```

**Comment by kookma** [comment] 2023-03-23 16:58
Appearanly the issue is in 
$:/core/ui/EditorToolbar/preview-type-dropdown

I added a `</$reveal>` at the end of macro and it works

```
.
.

</$reveal>
\end
.
.
.
```

**Comment by flibbles** [comment] 2023-03-23 17:06
I've isolated it. $Reveal must be doing its own thing. I'll fix it when I have a moment.

**Comment by flibbles** [comment] 2023-03-23 17:09
...and seeing as how this problem doesn't show up in v5.2.5, it looks like a regression in core, so the fix will probably go there once I find it.

**Comment by kookma** [comment] 2023-03-23 18:38
That is true! I have not the problem in 5.2.5 or earlier version. 

Side note:
I checked the code in `$:/core/ui/EditorToolbar/preview-type-dropdown` it seems it belongs to years ago! The readability for 5.2.6 is not good at all and I think it can be improved.

**Comment by flibbles** [comment] 2023-03-23 22:22
All right. [I've pushed a fix to core.](https://github.com/Jermolene/TiddlyWiki5/pull/7371) Now it's up to them to merge. It's out of my hands.

**Closed as completed by flibbles** 2023-03-23 22:23 UTC
